spring.application.name=VedantaTech
spring.datasource.url=jdbc:mysql://localhost:3306/vedantatech
spring.datasource.username=root
spring.datasource.password=Pavya@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true